FROM ubuntu:jammy

EXPOSE 5000

ENV ASPNETCORE_ENVIRONMENT="Production"
ENV ASPNETCORE_URLS="http://*:5000"

RUN \
  apt-get -y update && \
  apt-get -y install \
  apt-utils \
  wget \
  apt-transport-https \
  unzip \
  acl \
  libssl1.0

RUN \
  apt-get -y install aspnetcore-runtime-8.0

RUN \
  mkdir -p /app && \
  mkdir /config && \
  wget -q https://github.com/immense/Pronetsys/releases/latest/download/Pronetsys_Server_Linux-x64.zip && \
  unzip -o Pronetsys_Server_Linux-x64.zip -d /app && \
  rm Pronetsys_Server_Linux-x64.zip

RUN \
  mkdir -p /pronetsys-data && \
  sed -i 's/DataSource=Pronetsys.db/DataSource=\/pronetsys-data\/Pronetsys.db/' /app/appsettings.json

VOLUME "/pronetsys-data"

WORKDIR /app

COPY DockerMain.sh /

RUN chmod 755 /DockerMain.sh

ENTRYPOINT ["/DockerMain.sh"]